name: Ubinco
favicon: null
layout_spectrum: 0.9342573992908001
typography_spectrum: 0.631729285698384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3331642479170114
  lightness: 0.055828770622611046
  saturation: 0.46586677455343306
  rhythmicContrast: 0.5809437404386699
purpose: []
