name: Ubinco
favicon: null
layout_spectrum: 0
typography_spectrum: 0.64948
title: "Dikke terug aan't lopen"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
